KeinProblem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('menu.urls', 'menu'), namespace='menu'))
]

menu/urls.py
from django.urls import path
from . import views

app_name = "menu"
urlpatterns = [
    path("", views.index, name="index"),
    path("dQuiz", views.dQuiz, name="dQuiz"),
    path("api/words", views.Qwords, name="Qwords")
]

menu/models.py
from django.db import models

# Create your models here.

# slowka


class Btwo(models.Model):
  deu = models.CharField(max_length=2048)
  qnu = models.IntegerField(blank=True, null=True)
  day = models.IntegerField(blank=True, null=True)
  week = models.IntegerField(blank=True, null=True)
  bed = models.CharField(max_length=2048, blank=True, null=True)
  art = models.IntegerField(blank=True, null=True)
  dif = models.IntegerField(blank=True, null=True)
  typ = models.CharField(max_length=2048, blank=True, null=True)

  def __str__(self):
    return f"{self.deu}"

menu/views.py
from django.shortcuts import HttpResponse, render
from .models import Btwo
from django.http import JsonResponse

# Create your views here.


def index(request):
  return render(request, "menu/index.html", {"Btwo": Btwo.objects.all()})


def dQuiz(request):
  return render(request, "menu/dQuiz.html", {"Btwo": Btwo.objects.all()})


## Btwo.objects.all() DO UZYCIA W ZUKUNFT

xxx = 1
yyy = 2
zzz = "test"
vvv = 3


def Qwords(request):
  Rwords = {'day': xxx, 'week': yyy, 'word': zzz, 'art': vvv}
  return HttpResponse("Hallo Welt")

menu/templates/menu/dQuiz.html
{% extends "menu/wzor.html" %}

{% block cialo %}

      
<h2>Der, die or das??? Versuchen Sie zu erraten!!!</h2>

<div>

  {% for i in Btwo %}
        {% if i.qnu == 20 and i.day == 1 and i.week == 1 %}
   <h1>{{i.deu}}</h1>
        {% endif %}
  {% endfor %}


<button class="QuizBu">DER</button>
<button class="QuizBu">DIE</button>
<button class="QuizBu" >DAS</button>
<button id="senreq">TEST</button>
<div id="Empfenger">???</div>
            
</div>

  


{% endblock %}

menu/templates/menu/index.html
{% extends "menu/wzor.html" %}

{% block cialo %}




      <h2>Choose set of words </h2>

<div id ="selectors">
<select name="Week" id="Week">
       
  <option value="1"">1</option>
      <option value="2"">2</option>
      <option value="3"">3</option>
      <option value="4"">4</option>
      <option value="5"">5</option>
      <option value="6"">6</option>
      <option value="7"">7</option>
      <option value="8"">8</option>
      <option value="9"">9</option>
      <option value="10"">10</option>
      <option value="11"">11</option>
      <option value="12"">12</option>
      <option value="13"">13</option>
      <option value="14"">14</option>
      <option value="15"">15</option>
      

</select>

<select name="Day" id="Day">
  <option value="1">1</option>
  <option value="2">2</option>
  <option value="3">3</option>
  <option value="4">4</option>
<option value="5">5</option>
<option value="6">6</option>
<option value="7">7</option>
<option value="all">All</option>
</select>

<button id="GO">GO</button>
</div>


     
            
      <div style="background-color: #2c3e50; padding: 30px; margin: 40px; color: white; border-radius: 25px;">
      <ol>
      {% for i in Btwo %}
       <li class="words" data-day="{{ i.day }}" data-week="{{ i.week }}">{{i.deu}}</li>
      {% endfor %}
      </ol> 
           
      </div>
      
      



{% endblock %}
    

menu/templates/menu/wzor.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="{% static 'menu/menu.js' %}"></script>
  <script src="{% static 'quiz/quiz.js' %}"></script>
  <link rel="stylesheet" href="{% static 'menu/style.css' %}">
  <title>Kein Problem</title>
</head>

<body>
  <header>
    <h1>Kein Problem</h1>
  </header>

  <main>
    <aside class="sidebar">
      <nav>
        <ul>
          <li><a href="{% url 'menu:index' %}">Home</a></li>
          <li><a href="#">Learning goals</a></li>
          <li><a href="#">Add vocab</a></li>
          <li><a href="{% url 'menu:dQuiz' %}">der die das Quiz</a></li>
          <li><a href="#">Difficult words</a></li>
          <li><a href="#">Vocab themes</a></li>
          <li><a href="#">Usefull links</a></li>
        </ul>
      </nav>
    </aside>

    <section class="content">



      {% block cialo %}
      {% endblock %}

      
    </section>
  </main>

  <footer>
    <p>Contact: nonsense@gmail.com | © 2025 KeinProblem</p>
  </footer>

</body>